---
# tasks file for apache
- name: install HTTP Server
  yum: name=httpd state=present

- name: Create sites directory
  file: path={{item}} state=directory
  with_items: "{{apache_dirs}}"

- name: copy and index.html
  template: src=index.html.j2 dest={{apache_docroot}}/index.html

- name: copy httpd conf
  template: src=httpd.conf-{{ansible_os_family}}.j2 dest={{apache_config}}
  notify: restart httpd

- name: start HTTP Server 
  service: name=httpd state=started enabled=yes